
# - name: print to stdout
#   command: echo "{{ testvar }}"
#   register: hello

# - debug: msg="{{ hello.stdout }}"

- debug: msg=" Please check the parameter in /home/ec2-user/terraform/aws-cicd-iac/qa-cross-account/terraform.tfvar file before running the playbook"

- name: select workspace
  shell: "terraform workspace select qa"
  args:
    chdir: /home/ec2-user/terraform/aws-cicd-iac/qa-cross-account

- name: terraform init and plan
  shell: "terraform init && terraform plan"
  args:
    chdir: /home/ec2-user/terraform/aws-cicd-iac/qa-cross-account

- name: run the terraform task  
  shell: "terraform apply -auto-approve"
  args:
    chdir: /home/ec2-user/terraform/aws-cicd-iac/qa-cross-account

- debug: msg="Please check bucket policy, ecr policy, pipeline policy & kms resource in AWS console"
